language: node_js
node_js:
  - "16"
sudo: required
services:
  - docker

before_install:
  - docker build -t alexkolva/new-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true alexkolva/new-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-730197300883"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_ID"
  secret_access_key: "$AWS_SECRET_KEY"




